export const ADD_PREJOIN_VIDEO_TRACK = 'ADD_PREJOIN_VIDEO_TRACK';

export const ADD_PREJOIN_AUDIO_TRACK = 'ADD_PREJOIN_AUDIO_TRACK';

export const ADD_PREJOIN_CONTENT_SHARING_TRACK
    = 'ADD_PREJOIN_CONTENT_SHARING_TRACK';

export const PREJOIN_START_CONFERENCE = 'PREJOIN_START_CONFERENCE';

export const SET_DEVICE_STATUS = 'SET_DEVICE_STATUS';

export const SET_PREJOIN_AUDIO_DISABLED = 'SET_PREJOIN_AUDIO_DISABLED';

export const SET_PREJOIN_AUDIO_MUTED = 'SET_PREJOIN_AUDIO_MUTED';

export const SET_PREJOIN_DEVICE_ERRORS = 'SET_PREJOIN_DEVICE_ERRORS';

export const SET_PREJOIN_PAGE_VISIBILITY = 'SET_PREJOIN_PAGE_VISIBILITY';

export const SET_PREJOIN_VIDEO_DISABLED = 'SET_PREJOIN_VIDEO_DISABLED';

export const SET_PREJOIN_VIDEO_MUTED = 'SET_PREJOIN_VIDEO_MUTED';

export const CONNECT_JANE_SOCKET_SERVER = 'CONNECT_JANE_SOCKET_SERVER';

export const UPDATE_REMOTE_PARTICIPANTS_STATUS = 'UPDATE_REMOTE_PARTICIPANTS_STATUS';
